Repository toolkit-for-ynab/toolkit-for-ynab, pull requests merged in 2021-06, with the labels that each got.

#2374 Bugfix: Make GOAL an actual column, so that the new progress bars look nice.
  src/extension/features/budget/budget-category-features/goal-container.css
  src/extension/features/budget/budget-category-features/index.js
  src/extension/features/budget/rows-height/compact.css
  src/extension/features/budget/rows-height/slim-fonts.css
  src/extension/features/budget/rows-height/slim.css
Labels: bug-fix, waiting for reporter

#2380 fix: overbudgeting warning not showing on spending goals (#2367)
  src/extension/features/budget/budget-category-features/display-target-goal-amount/index.css
  src/extension/features/budget/budget-category-features/display-target-goal-amount/index.js
  src/extension/features/budget/budget-category-features/display-target-goal-amount/settings.js
Labels: bug-fix, waiting for reporter

#2392 fix: paid in full credit card assist does not respect color blind mode
  src/extension/features/budget/check-credit-balances/index.css
  src/extension/features/general/colour-blind-mode/index.css
Labels: waiting for reporter

#2404 fix: total monthly goals includes funded spending goals (#2347)
  src/extension/features/budget/display-total-monthly-goals/index.js
Labels: bug-fix
